### ISSUE TITLE
Upgrade to latest ms-seo introduces crash?

### ISSUE THREAD

**Issue by DirkStevens** [DerMambo/ms-seo#51]
/Users/dirkstevens/.meteor/packages/meteor-tool/.1.1.2.wg5oyf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
						throw(ex);
						      ^
TypeError: undefined is not a function
    at __coffeescriptShare (packages/manuelschoebel:ms-seo/seo_collection.coffee:1:22)
    at /Users/dirkstevens/MadeWithWonder/albemarledreams/.meteor/local/build/programs/server/packages/manuelschoebel_ms-seo.js:22:4
    at /Users/dirkstevens/MadeWithWonder/albemarledreams/.meteor/local/build/programs/server/packages/manuelschoebel_ms-seo.js:53:3
    at /Users/dirkstevens/MadeWithWonder/albemarledreams/.meteor/local/build/programs/server/boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (/Users/dirkstevens/.meteor/packages/meteor-tool/.1.1.2.wg5oyf++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /Users/dirkstevens/MadeWithWonder/albemarledreams/.meteor/local/build/programs/server/boot.js:117:5
Exited with code: 8
Your application is crashing. Waiting for file change.

**Comment by DirkStevens** [comment]
Appeared to be iron:router version induced incompatability - nothing to do with ms-seo.
